version: '3.8'

services:
    backend:
        container_name: node-mongo
        restart: always
        build: .
        ports: 
            - "3000:8081"
        links:
            - mongo
        volumes:
            - .:/usr/src/app
    mongo:
        container_name: mongo-db
        image: mongo
        restart: unless-stopped
        ports:
            - "27017:27017"
        volumes:
        - "./var/lib/mysql"
